version: '3'

services:
    nginx:
        image: nginx:mainline-alpine
        ports:
            - 443:443
            - 80:80
        volumes:
            - ./nginx/certbot.conf:/etc/nginx/conf.d/
            - ./letsencrypt/etc/:/etc/letsencrypt/
            - ./letsencrypt/lib/:/var/lib/letsencrypt/
    certbot:
        image: certbot/certbot
        command: ['certonly', '-n', '--webroot', '-w', '/etc/letsencrypt/', '--agree-tos', '-m', '$EMAIL', '-d', '$DOMAIN']
        volumes:
            - ./letsencrypt/etc/:/etc/letsencrypt/
            - ./letsencrypt/lib/:/var/lib/letsencrypt/
        depends_on:
            - nginx
