version: "3"


services:
    nginx:
        image: nginx:stable-alpine
        # using shell variant to pass env variables
        command: /bin/sh -c "envsubst '$$DOMAIN' < /etc/nginx/conf.d/certbot.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        environment:
            - DOMAIN
        ports:
            - "443:443"
            - "80:80"
        volumes:
            - ./nginx/certbot.template:/etc/nginx/conf.d/certbot.template
            - ./letsencrypt/www/:/var/www/letsencrypt/
            - ./letsencrypt/etc/:/etc/letsencrypt/
            - ./letsencrypt/lib/:/var/lib/letsencrypt/

    certbot:
        image: certbot/certbot
        command: ["certonly", "-n", "--webroot", "-w", "/var/www/letsencrypt/", "--agree-tos", "-m", "$EMAIL", "-d", "$DOMAIN"]
        volumes:
            - ./letsencrypt/www/:/var/www/letsencrypt/
            - ./letsencrypt/etc/:/etc/letsencrypt/
            - ./letsencrypt/lib/:/var/lib/letsencrypt/
        depends_on:
            - nginx
